#!/usr/bin/env bash
# =============================================================================
# Install git hooks at repo root. Pre-commit runs per-package checks when
# utils/ is present. This script is the source of truth; generated hook
# always uses a valid "then exit 1" block to avoid bash syntax errors.
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"

if [ ! -d "$REPO_ROOT/.git" ] || [ ! -d "$HOOKS_DIR" ]; then
  echo "Not a git repository or .git/hooks missing. Skipping hook installation."
  exit 0
fi

# Package dir names from root package.json (@simpill/name.utils -> @simpill-name.utils)
PKG_NAMES=""
if [ -f "$REPO_ROOT/package.json" ]; then
  PKG_NAMES=$(node -e "
    const p = require('$REPO_ROOT/package.json');
    const deps = p.dependencies || {};
    const names = Object.keys(deps)
      .filter(k => k.startsWith('@simpill/') && k.endsWith('.utils'))
      .map(k => '@simpill-' + k.replace('@simpill/', '').replace('.utils', '') + '.utils');
    console.log(names.sort().join('\n'));
  " 2>/dev/null || true)
fi

# Build pre-commit hook. Each block must have "exit 1" in the then clause (no empty then).
PRE_COMMIT="$HOOKS_DIR/pre-commit"
cat > "$PRE_COMMIT" << 'HEADER'
#!/usr/bin/env bash
set -euo pipefail

# Package Pre-Commit Hook (generated by scripts/monorepo/install-hooks.sh)
REPO_ROOT="$(git rev-parse --show-toplevel)"

HEADER

while IFS= read -r dir; do
  [ -z "$dir" ] && continue
  # Use a single, valid block template: then clause always contains exit 1
  name="${dir#@simpill-}"
  name="${name%.utils}"
  cat >> "$PRE_COMMIT" << BLOCK

# --- BEGIN ${name}.utils ---
if [ -f "\$REPO_ROOT/utils/${dir}/scripts/pre-commit.sh" ]; then
  if git diff --cached --name-only | grep -q "^utils/${dir}/"; then
    if ! "\$REPO_ROOT/utils/${dir}/scripts/pre-commit.sh"; then
      exit 1
    fi
  fi
fi
# --- END ${name}.utils ---
BLOCK
done << EOF
$PKG_NAMES
EOF

echo "exit 0" >> "$PRE_COMMIT"
chmod +x "$PRE_COMMIT"
echo "Git hooks installed (pre-commit)."
