/** Shared (runtime-agnostic) logger utilities. */

export {
  isLoggerAdapter,
  type LoggerAdapter,
  type LoggerAdapterConfig,
} from "./adapter";
export {
  type BufferedAdapterConfig,
  BufferedLoggerAdapter,
  createBufferedAdapter,
} from "./buffered-adapter";
export {
  ANSI_COLORS,
  type AnsiColor,
  BOOLEAN_FALSY_VALUES,
  BOOLEAN_TRUTHY_VALUES,
  type BooleanFalsyValue,
  type BooleanTruthyValue,
  BUFFERED_ADAPTER_DEFAULTS,
  ENV_KEYS,
  type EnvKey,
  ERROR_KEYS,
  ERROR_MESSAGES,
  type ErrorKey,
  type ErrorMessage,
  FILE_TRANSPORT_DEFAULTS,
  type FileTransportDefault,
  LOG_FORMAT_VALUES,
  LOG_LEVEL,
  LOG_LEVEL_LOWER,
  LOG_PREFIX,
  LOGGER_CONTEXT,
  LOGGER_DEFAULTS,
  type LogFormatValue,
  type LoggableLevel,
  type LoggerContext,
  type LogLevel,
  type LogLevelLower,
  type LogPrefix,
  METADATA_KEYS,
  type MetadataKey,
  OUTPUT_CHARS,
  type OutputChar,
} from "./constants";
export {
  clearLogContextProvider,
  getLogContext,
  hasLogContextProvider,
  type LogContext,
  type LogContextProvider,
  setLogContextProvider,
  withLogContext,
} from "./context";
export {
  createFormatterFromEnv,
  ENV_DEFAULTS,
  type EnvLoggerConfig,
  envConfigToAdapterConfig,
  hasEnvConfig,
  loadAdapterConfigFromEnv,
  loadEnvConfig,
} from "./env.config";
export {
  clearLoggerCache,
  configureLogger,
  configureLoggerFactory,
  disableLoggerMock,
  enableLoggerMock,
  flushLogs,
  getLogger,
  getLoggerCacheSize,
  getRootLogger,
  isLoggerMockEnabled,
  LoggerFactory,
  resetLoggerFactory,
  setLoggerAdapter,
} from "./factory";
export {
  COLORS,
  ColoredFormatterAdapter,
  type ColoredFormatterConfig,
  coloredFormatter,
  createColoredFormatter,
  createFormatter,
  createFormatterContext,
  createSimpleFormatter,
  defaultFormatter,
  type FormattedOutput,
  type FormatterAdapter,
  type FormatterContext,
  type FormatterOptions,
  formatWithAdapter,
  isFormatterAdapter,
  jsonFormatter,
  jsonFormatterAdapter,
  minimalFormatter,
  outputToString,
  SimpleFormatterAdapter,
  type SimpleFormatterConfig,
  serializeMetadata,
  simpleFormatter,
  timestampFormatter,
  verboseFormatter,
} from "./formatters";
export { createSimpleAdapter, SimpleLoggerAdapter } from "./simple-adapter";
export {
  type ErrorInfo,
  extractErrorInfo,
  isErrorLike,
  LOG_LEVEL_PRIORITY,
  type Log,
  type LogEntry,
  type LogFormatter,
  type Logger,
  type LoggerOptions,
  type LogMetadata,
  type LogWriter,
  normalizeErrorsInMetadata,
  shouldLog,
} from "./types";
