/**
 * Client/Edge exports for @simpill/object.utils.
 * Re-exports shared (runtime-agnostic) object utilities.
 */

export type {
  BoundedArrayLogger,
  BoundedArrayOptions,
  BoundedArrayStats,
  BoundedLRUMapLogger,
  BoundedLRUMapOptions,
  BoundedLRUMapStats,
  DeepMergeOptions,
  DeepPartial,
  DeepReadonly,
  DeepRequired,
  Entries,
  KeysOfType,
  Mutable,
  NonStringKeys,
  PartialBy,
  PathValue,
  ReadonlyShallow,
  RecordWithKnownKeys,
  RequiredBy,
  StrictRecord,
  StringKeys,
  ValueOf,
} from "../shared";
export {
  BoundedArray,
  BoundedLRUMap,
  createSingleton,
  createWithDefaults,
  deepFreeze,
  deepMerge,
  deepSeal,
  defineReadOnly,
  fromEntries,
  getByPath,
  getByPathOrDefault,
  hasPath,
  hasOwn,
  isDefined,
  isEmptyObject,
  isNil,
  isObject,
  isPlainObject,
  isRecord,
  omit,
  pick,
  pickOne,
  resetAllSingletons,
  resetSingleton,
  setByPath,
  shallowMerge,
} from "../shared";
